[project]
name = "paper2code"
version = "1.0.0"
author = "Kushvinth Madhavan"
description = "Practical Implementation Of Machine Learning Papers"
requires-python = ">=3.8"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=1.24.4",
    "uv>=0.8.13",
]
